server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.25.128
aliyun:
  sms:
    accessKeyId: LTAIac4p8qHNx5x2
    accessKeySecret: XXXXXXXXXXXXXXXXXXXX
    template_code: SMS_85735065
    sign_name: 黑马